version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: directus_password
      POSTGRES_DB: directus
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  directus:
    image: directus/directus:11.2.2
    restart: always
    depends_on:
      - postgres
    environment:
      KEY: 255d861b-5ea1-5996-9aa3-922530ec40b1
      SECRET: 6116487b-cda1-52c2-b5b5-c8022c45e263
      DB_CLIENT: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: postgres
      DB_PASSWORD: directus_password
      ADMIN_EMAIL: admin@roboflow.tech
      ADMIN_PASSWORD: admin123456
      CORS_ENABLED: true
      CORS_ORIGIN: true
      CORS_METHODS: GET,POST,PATCH,DELETE
      CORS_ALLOWED_HEADERS: Content-Type,Authorization
      CORS_EXPOSED_HEADERS: Content-Range
      CORS_CREDENTIALS: true
      CORS_MAX_AGE: 18000
    volumes:
      - ./directus_uploads:/directus/uploads
    ports:
      - "8055:8055"