version: '3'

services:
  smm:
    build:
      context: ./smm
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./smm:/app
      - smm_node_modules:/app/node_modules  # Используем именованный том вместо анонимного
    environment:
      - GEMINI_API_KEY=AIzaSyDaYtWfHwI9vq3kTatny217HnbKauAvdxE
      - NODE_ENV=development
      - BEGET_S3_ACCESS_KEY=${BEGET_S3_ACCESS_KEY}
      - BEGET_S3_SECRET_KEY=${BEGET_S3_SECRET_KEY}
      - BEGET_S3_BUCKET=${BEGET_S3_BUCKET}
      - BEGET_S3_ENDPOINT=${BEGET_S3_ENDPOINT:-https://s3.ru1.storage.beget.cloud}
      - BEGET_S3_REGION=${BEGET_S3_REGION:-ru-1}
      - AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE=1
    command: npm run dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.smm.rule=Host(`smm.nplanner.ru`)
      - traefik.http.routers.smm.tls=true
      - traefik.http.routers.smm.entrypoints=web,websecure
      - traefik.http.routers.smm.tls.certresolver=mytlschallenge
      - traefik.http.services.smm.loadbalancer.server.port=5000

# Определяем именованные тома
volumes:
  smm_node_modules: